name: Unity CI

on: [push, pull_request]

env:                        # centralise versions & paths
  UNITY_VERSION: 6000.0.52f1
  PROJECT_PATH: .

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1 Check out code
    - uses: actions/checkout@v4

    # 2 Install Unity via Game-CI, logging in with your email/password
    - name: Install Unity
      uses: game-ci/unity-installer@v2   # ← was @v3
      with:
        unityVersion: ${{ env.UNITY_VERSION }}
        modules: webgl
        unityEmail: ${{ secrets.UNITY_EMAIL }}
        unityPassword: ${{ secrets.UNITY_PASSWORD }}
        githubToken: ${{ secrets.GITHUB_TOKEN }}

    # 3 Build WebGL player (empty scene is fine)
    - name: Build WebGL
      uses: game-ci/unity-builder@v2     # ← was @v3
      with:
        unityVersion: ${{ env.UNITY_VERSION }}
        targetPlatform: WebGL
        projectPath: ${{ env.PROJECT_PATH }}

    # 4 Upload build artifact
    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: WebGL-Build
        path: build/WebGL
